name: Check merged to staging
on:
  - pull_request
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: ferblape/merged-to-staging-action@v1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
