name: Check merged to staging

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: ferblape/merged-to-staging-action@v1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
